<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.16">
  <POU Name="MAIN" Id="{05fb79fc-cb93-42b1-8606-c8378de38b2a}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	Signal		:	Signal_generator;
	out			:	BOOL;
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Signal();
out := Signal.SIGNAL;]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="19" Count="0" />
      <LineId Id="23" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>